# Generated by cucumber_scaffold - http://github.com/andyw8/cucumber_scaffold

Given /^a project exists$/ do
  @project = Project.create!(valid_project_attributes)
end

Then /^I should see the following project:$/ do |expected_table|
  
  
  show_fields_css_query = 'body p b'
  
  
  actual_table = tableish(show_fields_css_query, lambda{|label| [label, label.next]})   
  actual = {}
  actual_table.each do |form_entry|
    attr_name = form_entry[0]
    attr_value = form_entry[1]
    actual[attr_name] = attr_value
  end
  assert_equal actual, expected_table.rows_hash
end

Then /^I should see the following projects:$/ do |expected_table|
  expected_table.diff!(tableish('ul.titleInactive', 'li'))
end

Given /^the following projects:$/ do |table|
  hashes = replace_spaces_with_underscores_in_keys(table.hashes)
  @projects = Project.create!(hashes)
end

Given /^the following project:$/ do |table|
  hashes = replace_spaces_with_underscores_in_keys(table.rows_hash)
  @project = Project.create!(hashes)
end

def valid_project_attributes
  # You may want to a factory for this
  {}
end
