# Generated by cucumber_scaffold - http://github.com/andyw8/cucumber_scaffold

Feature: Manage customers
  In order to [goal]
  [stakeholder]
  wants [behaviour]

    Scenario: List all customers
      Given the following customers:
        | name | shortname | website | 
        | name 1 | shortname 1 | website 1 | 
        | name 2 | shortname 2 | website 2 | 
        | name 3 | shortname 3 | website 3 | 
      When I go to the customers page
      Then I should see the following customers:
        | Name | Shortname | Website | 
        | name 1 | shortname 1 | website 1 | 
        | name 2 | shortname 2 | website 2 | 
        | name 3 | shortname 3 | website 3 |
      And the heading should be "Listing customers"
      

    Scenario: View a customer
      Given the following customers:
        | name | shortname | website |
        | name 1 | shortname 1 | website 1 | 
        | name 2 | shortname 2 | website 2 |
        | name 3 | shortname 3 | website 3 |
      When I go to the customers page
      And I click "Show" in the 2nd row
      Then I should see the following customer:
        | Name: | name 2 |
        | Shortname: | shortname 2 |
        | Website: | website 2 |
                  
      When I follow "Back"
      
      Then I should be on the customers page

    Scenario: Edit a customer
      Given the following customer:
        | name | name 10 |
        | shortname | shortname 10 |
        | website | website 10 |
      When I go to the page for that customer
      And I follow "Edit"
      Then I should see the following form field values:
        | Name | name 10 |
        | Shortname | shortname 10 |
        | Website | website 10 |
      Then the heading should be "Editing customer"
      
      When I follow "Show"
      Then I should be on the page for that customer

    Scenario: Delete a customer via the index page
      Given the following customers:
        | name | shortname | website | 
        | name 1 | shortname 1 | website 1 | 
        | name 2 | shortname 2 | website 2 | 
        | name 3 | shortname 3 | website 3 |
      When I go to the customers page
      And I click "Destroy" in the 2nd row
      Then I should see the following customers:
        | Name | Shortname | Website | 
        | name 1 | shortname 1 | website 1 | 
        | name 3 | shortname 3 | website 3 |
      And I should be on the customers page
      
    
    Scenario: New customer page  
      Given I am on the customers page
      When I follow "New Customer"
      Then I should be on the new customer page
      
      When I follow "Back"
      Then I should be on the customers page

    Scenario: Create a new customer
      Pending
      # Given I am on the new customer page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Shortname | shortname 10 |
        # | Website | website 10 |
      # And I press "Create"
      # Then I should see "Customer was successfully created."
      # And I should see the following customer:
      #   | Name: | name 10 |
        # | Shortname: | shortname 10 |
        # | Website: | website 10 |

    Scenario: Attempt to create a new customer with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given I am on the new customer page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Shortname | shortname 10 |
        # | Website | website 10 |
      # And I press "Create"
      # Then I should see "1 error prohibited this customer from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Shortname | shortname 10 |
        # | Website | website 10 |

    Scenario: Attempt to update a customer with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given a customer exists
      # When I go to the edit page for that customer
      # And I fill in the form with:
      #   | Name | name 10 |
        # | Shortname | shortname 10 |
        # | Website | website 10 |
      # And I press "Update"
      # Then I should see "1 error prohibited this customer from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Shortname | shortname 10 |
        # | Website | website 10 |

    Scenario: Update a customer
      Given the following customer:
        | name | name 10 |
        | shortname | shortname 10 |
        | website | website 10 |
      When I go to the edit page for that customer
      And I fill in the form with:
        | Name | name 10 updated |
        | Shortname | shortname 10 updated |
        | Website | website 10 updated | 
      And I press "Save"
      Then I should be on the page for that customer
      And I should see "Customer was successfully updated."
      And I should see the following customer:
        | Name: | name 10 updated |
        | Shortname: | shortname 10 updated |
        | Website: | website 10 updated |

    Scenario: Navigate from customers page to the edit customer page
      Given the following customers:
        | name | shortname | website | 
        | name 1 | shortname 1 | website 1 | 
        | name 2 | shortname 2 | website 2 | 
        | name 3 | shortname 3 | website 3 |
      When I go to the customers page
      And I click "Edit" in the 2nd row
      Then I should be on the edit page for the 2nd customer

    Scenario: Navigate from edit customer page to the customers page
      Given a customer exists
      When I go to the edit page for that customer
      And I follow "Back"
      Then I should be on the customers page