# Generated by cucumber_scaffold - http://github.com/andyw8/cucumber_scaffold

Feature: Manage locations
  In order to [goal]
  [stakeholder]
  wants [behaviour]

    Scenario: List all locations
      Given the following customers:
        | name | shortname | website | id |
        | name 1 | shortname 1 | website 1 | 1 |
        | name 2 | shortname 2 | website 2 | 2 |
        | name 3 | shortname 3 | website 3 | 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | name 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | name 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | name 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 | 
      When I go to the locations page
      And I should see the following locations:
        | Name | Street | Zip | City | Fon | Fax | Customer | 
        | name 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | name 1 | 
        | name 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | name 2 | 
        | name 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | name 3 |
      And the heading should be "Listing locations"
      

    Scenario: View a location
      Given the following customers:
        | name | shortname | website | id |
        | name 1 | shortname 1 | website 1 | 1 |
        | name 2 | shortname 2 | website 2 | 2 |
        | name 3 | shortname 3 | website 3 | 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | name 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | name 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | name 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      When I go to the locations page
      And I click "Show" in the 2nd row
      Then I should see the following location:
        | Name: | name 2 |
        | Street: | street 2 |
        | Zip: | 12 |
        | City: | city 2 |
        | Fon: | fon 2 |
        | Fax: | fax 2 |
        | Customer: | name 2 |
      When I follow "Back"
      Then I should be on the locations page

    Scenario: Edit a location
      Given the following customer:
        | name | name 1 |
        | shortname | shortname 1 |
        | website | website 1 |
        | id | 1 |
      And the following location:
        | name | name 10 |
        | street | street 10 |
        | zip | 20 |
        | city | city 10 |
        | fon | fon 10 |
        | fax | fax 10 |
        | customer_id | 1 |
      When I go to the page for that location
      And I follow "Edit"
      Then I should see the following form field values:
        | Name | name 10 |
        | Street | street 10 |
        | Zip | 20 |
        | City | city 10 |
        | Fon | fon 10 |
        | Fax | fax 10 |
        | Customer | |
      Then the heading should be "Editing location"
      
      When I follow "Show"
      Then I should be on the page for that location

    Scenario: Delete a location via the index page
      Given the following customers:
        | name | shortname | website | id |
        | name 1 | shortname 1 | website 1 | 1 |
        | name 2 | shortname 2 | website 2 | 2 |
        | name 3 | shortname 3 | website 3 | 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | name 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | name 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | name 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      When I go to the locations page
      And I click "Destroy" in the 2nd row
      Then I should see the following locations:
        | Name | Street | Zip | City | Fon | Fax | Customer | 
        | name 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | name 1 | 
        | name 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | name 3 |
      And I should be on the locations page
      
    
    Scenario: New location page  
      Given I am on the locations page
      When I follow "New Location"
      Then I should be on the new location page
      
      When I follow "Back"
      Then I should be on the locations page

    Scenario: Create a new location
      Pending
      # Given I am on the new location page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Street | street 10 |
        # | Zip | 20 |
        # | City | city 10 |
        # | Fon | fon 10 |
        # | Fax | fax 10 |
        # | Customer | #<Customer:0x00000103632f00> |
      # And I press "Create"
      # Then I should see "Location was successfully created."
      # And I should see the following location:
      #   | Name: | name 10 |
        # | Street: | street 10 |
        # | Zip: | 20 |
        # | City: | city 10 |
        # | Fon: | fon 10 |
        # | Fax: | fax 10 |
        # | Customer: | #<Customer:0x0000010362af80> |

    Scenario: Attempt to create a new location with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given I am on the new location page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Street | street 10 |
        # | Zip | 20 |
        # | City | city 10 |
        # | Fon | fon 10 |
        # | Fax | fax 10 |
        # | Customer | #<Customer:0x00000103621ca0> |
      # And I press "Create"
      # Then I should see "1 error prohibited this location from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Street | street 10 |
        # | Zip | 20 |
        # | City | city 10 |
        # | Fon | fon 10 |
        # | Fax | fax 10 |
        # | Customer | #<Customer:0x00000103619eb0> |

    Scenario: Attempt to update a location with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given a location exists
      # When I go to the edit page for that location
      # And I fill in the form with:
      #   | Name | name 10 |
        # | Street | street 10 |
        # | Zip | 20 |
        # | City | city 10 |
        # | Fon | fon 10 |
        # | Fax | fax 10 |
        # | Customer | #<Customer:0x00000103611030> |
      # And I press "Update"
      # Then I should see "1 error prohibited this location from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Street | street 10 |
        # | Zip | 20 |
        # | City | city 10 |
        # | Fon | fon 10 |
        # | Fax | fax 10 |
        # | Customer | #<Customer:0x0000010360a5f0> |

    Scenario: Update a location
      Given the following customer:
        | name | name 1 |
        | shortname | shortname 1 |
        | website | website 1 |
        | id | 1 |
      And the following location:
        | name | name 10 |
        | street | street 10 |
        | zip | 20 |
        | city | city 10 |
        | fon | fon 10 |
        | fax | fax 10 |
        | customer_id | 1 |
      When I go to the edit page for that location
      And I fill in the form with:
        | Name | name 10 updated |
        | Street | street 10 updated |
        | Zip | -20 |
        | City | city 10 updated |
        | Fon | fon 10 updated |
        | Fax | fax 10 updated |
      And I press "Save"
      Then I should be on the page for that location
      And I should see "Location was successfully updated."
      And I should see the following location:
        | Name: | name 10 updated |
        | Street: | street 10 updated |
        | Zip: | -20 |
        | City: | city 10 updated |
        | Fon: | fon 10 updated |
        | Fax: | fax 10 updated |
        | Customer: | name 1 |

    Scenario: Navigate from locations page to the edit location page
      Given the following customers:
        | name | shortname | website | id |
        | name 1 | shortname 1 | website 1 | 1 |
        | name 2 | shortname 2 | website 2 | 2 |
        | name 3 | shortname 3 | website 3 | 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | name 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | name 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | name 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      When I go to the locations page
      And I click "Edit" in the 2nd row
      Then I should be on the edit page for the 2nd location

    Scenario: Navigate from edit location page to the locations page
      Given the following customer:
        | name | name 1 |
        | shortname | shortname 1 |
        | website | website 1 |
        | id | 1 |
      And the following location:
        | name | name 10 |
        | street | street 10 |
        | zip | 20 |
        | city | city 10 |
        | fon | fon 10 |
        | fax | fax 10 |
        | customer_id | 1 |
      When I go to the edit page for that location
      And I follow "Back"
      Then I should be on the locations page