# Generated by cucumber_scaffold - http://github.com/andyw8/cucumber_scaffold

Feature: Manage contacts
  In order to [goal]
  [stakeholder]
  wants [behaviour]

    Scenario: List all contacts
      Given the following customers:
        | name | shortname | website |
        | name 1 | shortname 1 | website 1 |
        | name 2 | shortname 2 | website 2 |
        | name 3 | shortname 3 | website 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | location 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | location 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | location 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      And the following contacts:
        | salutation | title | firstname | lastname | department | email | fon | mobile | fax | location_id | 
        | salutation 1 | title 1 | firstname 1 | lastname 1 | department 1 | email 1 | fon 1 | mobile 1 | fax 1 | 1 | 
        | salutation 2 | title 2 | firstname 2 | lastname 2 | department 2 | email 2 | fon 2 | mobile 2 | fax 2 | 2 | 
        | salutation 3 | title 3 | firstname 3 | lastname 3 | department 3 | email 3 | fon 3 | mobile 3 | fax 3 | 3 | 
      When I go to the contacts page
      Then I should see the following contacts:
        | Salutation | Title | Firstname | Lastname | Department | Email | Fon | Mobile | Fax | Location | 
        | salutation 1 | title 1 | firstname 1 | lastname 1 | department 1 | email 1 | fon 1 | mobile 1 | fax 1 | location 1 | 
        | salutation 2 | title 2 | firstname 2 | lastname 2 | department 2 | email 2 | fon 2 | mobile 2 | fax 2 | location 2 | 
        | salutation 3 | title 3 | firstname 3 | lastname 3 | department 3 | email 3 | fon 3 | mobile 3 | fax 3 | location 3 |
      And the heading should be "Listing contacts"
      

    Scenario: View a contact
      Given the following customers:
        | name | shortname | website |
        | customer 1 | shortname 1 | website 1 |
        | customer 2 | shortname 2 | website 2 |
        | customer 3 | shortname 3 | website 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | location 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | location 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | location 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      And the following contacts:
        | salutation | title | firstname | lastname | department | email | fon | mobile | fax | location_id | 
        | salutation 1 | title 1 | firstname 1 | lastname 1 | department 1 | email 1 | fon 1 | mobile 1 | fax 1 | 1 | 
        | salutation 2 | title 2 | firstname 2 | lastname 2 | department 2 | email 2 | fon 2 | mobile 2 | fax 2 | 2 | 
        | salutation 3 | title 3 | firstname 3 | lastname 3 | department 3 | email 3 | fon 3 | mobile 3 | fax 3 | 3 |
      When I go to the contacts page
      And I click "Show" in the 2nd row
      Then I should see the following contact:
        | Salutation: | salutation 2 |
        | Title: | title 2 |
        | Firstname: | firstname 2 |
        | Lastname: | lastname 2 |
        | Department: | department 2 |
        | Email: | email 2 |
        | Fon: | fon 2 |
        | Mobile: | mobile 2 |
        | Fax: | fax 2 |
        | Location: | location 2 |
      When I follow "Back"
      Then I should be on the contacts page

    Scenario: Edit a contact
      Given the following customer:
        | name | customer 1 |
        | shortname | shortname 1 |
        | website | website 1 |
      And the following location:
        | name | location 1 |
        | street | street 10 |
        | zip | 20 |
        | city | city 10 |
        | fon | fon 10 |
        | fax | fax 10 |
        | customer_id | 1 |
      And the following contact:
        | salutation | salutation 10 |
        | title | title 10 |
        | firstname | firstname 10 |
        | lastname | lastname 10 |
        | department | department 10 |
        | email | email 10 |
        | fon | fon 10 |
        | mobile | mobile 10 |
        | fax | fax 10 |
        | location_id | 1 |
      When I go to the page for that contact
      And I follow "Edit"
      Then I should see the following form field values:
        | Salutation | salutation 10 |
        | Title | title 10 |
        | Firstname | firstname 10 |
        | Lastname | lastname 10 |
        | Department | department 10 |
        | Email | email 10 |
        | Fon | fon 10 |
        | Mobile | mobile 10 |
        | Fax | fax 10 |
        | Location | |
      Then the heading should be "Editing contact"
      
      When I follow "Show"
      Then I should be on the page for that contact

    Scenario: Delete a contact via the index page
      Given the following customers:
        | name | shortname | website |
        | customer 1 | shortname 1 | website 1 |
        | customer 2 | shortname 2 | website 2 |
        | customer 3 | shortname 3 | website 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | location 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | location 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | location 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      And the following contacts:
        | salutation | title | firstname | lastname | department | email | fon | mobile | fax | location_id | 
        | salutation 1 | title 1 | firstname 1 | lastname 1 | department 1 | email 1 | fon 1 | mobile 1 | fax 1 | 1 | 
        | salutation 2 | title 2 | firstname 2 | lastname 2 | department 2 | email 2 | fon 2 | mobile 2 | fax 2 | 2 | 
        | salutation 3 | title 3 | firstname 3 | lastname 3 | department 3 | email 3 | fon 3 | mobile 3 | fax 3 | 3 |
      When I go to the contacts page
      And I click "Destroy" in the 2nd row
      Then I should see the following contacts:
        | Salutation | Title | Firstname | Lastname | Department | Email | Fon | Mobile | Fax | Location | 
        | salutation 1 | title 1 | firstname 1 | lastname 1 | department 1 | email 1 | fon 1 | mobile 1 | fax 1 | location 1 | 
        | salutation 3 | title 3 | firstname 3 | lastname 3 | department 3 | email 3 | fon 3 | mobile 3 | fax 3 | location 3 |
      And I should be on the contacts page
      
    
    Scenario: New contact page  
      Given I am on the contacts page
      When I follow "New Contact"
      Then I should be on the new contact page
      
      When I follow "Back"
      Then I should be on the contacts page

    Scenario: Create a new contact
      Pending
      # Given I am on the new contact page
      # When I fill in the form with:
      #   | Salutation | salutation 10 |
        # | Title | title 10 |
        # | Firstname | firstname 10 |
        # | Lastname | lastname 10 |
        # | Department | department 10 |
        # | Email | email 10 |
        # | Fon | fon 10 |
        # | Mobile | mobile 10 |
        # | Fax | fax 10 |
        # | Location | #<Location:0x00000103deff90> |
      # And I press "Create"
      # Then I should see "Contact was successfully created."
      # And I should see the following contact:
      #   | Salutation: | salutation 10 |
        # | Title: | title 10 |
        # | Firstname: | firstname 10 |
        # | Lastname: | lastname 10 |
        # | Department: | department 10 |
        # | Email: | email 10 |
        # | Fon: | fon 10 |
        # | Mobile: | mobile 10 |
        # | Fax: | fax 10 |
        # | Location: | #<Location:0x0000010576dc38> |

    Scenario: Attempt to create a new contact with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given I am on the new contact page
      # When I fill in the form with:
      #   | Salutation | salutation 10 |
        # | Title | title 10 |
        # | Firstname | firstname 10 |
        # | Lastname | lastname 10 |
        # | Department | department 10 |
        # | Email | email 10 |
        # | Fon | fon 10 |
        # | Mobile | mobile 10 |
        # | Fax | fax 10 |
        # | Location | #<Location:0x00000105762c98> |
      # And I press "Create"
      # Then I should see "1 error prohibited this contact from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Salutation | salutation 10 |
        # | Title | title 10 |
        # | Firstname | firstname 10 |
        # | Lastname | lastname 10 |
        # | Department | department 10 |
        # | Email | email 10 |
        # | Fon | fon 10 |
        # | Mobile | mobile 10 |
        # | Fax | fax 10 |
        # | Location | #<Location:0x00000105759b20> |

    Scenario: Attempt to update a contact with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given a contact exists
      # When I go to the edit page for that contact
      # And I fill in the form with:
      #   | Salutation | salutation 10 |
        # | Title | title 10 |
        # | Firstname | firstname 10 |
        # | Lastname | lastname 10 |
        # | Department | department 10 |
        # | Email | email 10 |
        # | Fon | fon 10 |
        # | Mobile | mobile 10 |
        # | Fax | fax 10 |
        # | Location | #<Location:0x0000010574e2e8> |
      # And I press "Update"
      # Then I should see "1 error prohibited this contact from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Salutation | salutation 10 |
        # | Title | title 10 |
        # | Firstname | firstname 10 |
        # | Lastname | lastname 10 |
        # | Department | department 10 |
        # | Email | email 10 |
        # | Fon | fon 10 |
        # | Mobile | mobile 10 |
        # | Fax | fax 10 |
        # | Location | #<Location:0x0000010573f450> |

    Scenario: Update a contact
      Given the following customer:
        | name | customer 1 |
        | shortname | shortname 1 |
        | website | website 1 |
      And the following location:
        | name | location 1 |
        | street | street 10 |
        | zip | 20 |
        | city | city 10 |
        | fon | fon 10 |
        | fax | fax 10 |
        | customer_id | 1 |
      And the following contact:
        | salutation | salutation 10 |
        | title | title 10 |
        | firstname | firstname 10 |
        | lastname | lastname 10 |
        | department | department 10 |
        | email | email 10 |
        | fon | fon 10 |
        | mobile | mobile 10 |
        | fax | fax 10 |
        | location_id | 1 |
      When I go to the edit page for that contact
      And I fill in the form with:
        | Salutation | salutation 10 updated |
        | Title | title 10 updated |
        | Firstname | firstname 10 updated |
        | Lastname | lastname 10 updated |
        | Department | department 10 updated |
        | Email | email 10 updated |
        | Fon | fon 10 updated |
        | Mobile | mobile 10 updated |
        | Fax | fax 10 updated |
      And I press "Save"
      Then I should be on the page for that contact
      And I should see "Contact was successfully updated."
      And I should see the following contact:
        | Salutation: | salutation 10 updated |
        | Title: | title 10 updated |
        | Firstname: | firstname 10 updated |
        | Lastname: | lastname 10 updated |
        | Department: | department 10 updated |
        | Email: | email 10 updated |
        | Fon: | fon 10 updated |
        | Mobile: | mobile 10 updated |
        | Fax: | fax 10 updated |
        | Location: | location 1 |

    Scenario: Navigate from contacts page to the edit contact page
      Given the following customers:
        | name | shortname | website |
        | name 1 | shortname 1 | website 1 |
        | name 2 | shortname 2 | website 2 |
        | name 3 | shortname 3 | website 3 |
      And the following locations:
        | name | street | zip | city | fon | fax | customer_id | 
        | location 1 | street 1 | 11 | city 1 | fon 1 | fax 1 | 1 | 
        | location 2 | street 2 | 12 | city 2 | fon 2 | fax 2 | 2 | 
        | location 3 | street 3 | 13 | city 3 | fon 3 | fax 3 | 3 |
      And the following contacts:
        | salutation | title | firstname | lastname | department | email | fon | mobile | fax | location_id | 
        | salutation 1 | title 1 | firstname 1 | lastname 1 | department 1 | email 1 | fon 1 | mobile 1 | fax 1 | 1 | 
        | salutation 2 | title 2 | firstname 2 | lastname 2 | department 2 | email 2 | fon 2 | mobile 2 | fax 2 | 2 | 
        | salutation 3 | title 3 | firstname 3 | lastname 3 | department 3 | email 3 | fon 3 | mobile 3 | fax 3 | 3 |
      When I go to the contacts page
      And I click "Edit" in the 2nd row
      Then I should be on the edit page for the 2nd contact

    Scenario: Navigate from edit contact page to the contacts page
      Given the following customer:
        | name | customer 1 |
        | shortname | shortname 1 |
        | website | website 1 |
      And the following location:
        | name | location 1 |
        | street | street 10 |
        | zip | 20 |
        | city | city 10 |
        | fon | fon 10 |
        | fax | fax 10 |
        | customer_id | 1 |
      And the following contact:
        | salutation | salutation 10 |
        | title | title 10 |
        | firstname | firstname 10 |
        | lastname | lastname 10 |
        | department | department 10 |
        | email | email 10 |
        | fon | fon 10 |
        | mobile | mobile 10 |
        | fax | fax 10 |
        | location_id | 1 |
      When I go to the edit page for that contact
      And I follow "Back"
      Then I should be on the contacts page